--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Abril-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPTREE_TEMPTAB
--------------------------------------------------------

  CREATE TABLE "USER_DEV"."DEPTREE_TEMPTAB" 
   (	"OBJECT_ID" NUMBER, 
	"REFERENCED_OBJECT_ID" NUMBER, 
	"NEST_LEVEL" NUMBER, 
	"SEQ#" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USER_DEV.DEPTREE_TEMPTAB
SET DEFINE OFF;
Insert into USER_DEV.DEPTREE_TEMPTAB (OBJECT_ID,REFERENCED_OBJECT_ID,NEST_LEVEL,SEQ#) values ('20084','0','0','0');
Insert into USER_DEV.DEPTREE_TEMPTAB (OBJECT_ID,REFERENCED_OBJECT_ID,NEST_LEVEL,SEQ#) values ('20086','20084','1','18');
Insert into USER_DEV.DEPTREE_TEMPTAB (OBJECT_ID,REFERENCED_OBJECT_ID,NEST_LEVEL,SEQ#) values ('20091','20086','2','19');
