--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Abril-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEGMERCADO
--------------------------------------------------------

  CREATE TABLE "USER_DEV"."SEGMERCADO" 
   (	"ID" NUMBER(5,0), 
	"DESCRICAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USER_DEV.SEGMERCADO
SET DEFINE OFF;
Insert into USER_DEV.SEGMERCADO (ID,DESCRICAO) values ('1','VAREJISTA');
Insert into USER_DEV.SEGMERCADO (ID,DESCRICAO) values ('2','ATACADISTA');
Insert into USER_DEV.SEGMERCADO (ID,DESCRICAO) values ('3','FARMACEUTICO');
Insert into USER_DEV.SEGMERCADO (ID,DESCRICAO) values ('4','INDUSTRIAL');
Insert into USER_DEV.SEGMERCADO (ID,DESCRICAO) values ('5','AGROPECUARIA');
--------------------------------------------------------
--  DDL for Index SEGMERCADO_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_DEV"."SEGMERCADO_ID_PK" ON "USER_DEV"."SEGMERCADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEGMERCADO
--------------------------------------------------------

  ALTER TABLE "USER_DEV"."SEGMERCADO" ADD CONSTRAINT "SEGMERCADO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
