--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Abril-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "USER_DEV"."CLIENTE" 
   (	"ID" NUMBER(5,0), 
	"RAZAO_SOCIAL" VARCHAR2(100 BYTE), 
	"CNPJ" VARCHAR2(20 BYTE), 
	"SEGMERCADO_ID" NUMBER(5,0), 
	"DATA_INCLUSAO" DATE, 
	"FATURAMENTO_PREVISTO" NUMBER(10,2), 
	"CATEGORIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USER_DEV.CLIENTE
SET DEFINE OFF;
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('1','SUPERMERCADO XYZ','12/345','5',to_date('18/04/18','DD/MM/RR'),'150000','GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('2','SUPERMERCADO IJK','67/890','1',to_date('18/04/18','DD/MM/RR'),'90000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('3','SUPERMERCADO IJK','89/012','3',to_date('18/04/18','DD/MM/RR'),'80000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('4','FARMACIA AXZ','12/378','3',to_date('18/04/18','DD/MM/RR'),'80000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('5','PRIMEIRO CLIENTE INCLUIDO POR USER_APP','23/456','2',to_date('18/04/18','DD/MM/RR'),'100000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('6','SEGUNDO CLIENTE INCLUIDO POR USER_APP','23/456','2',to_date('18/04/18','DD/MM/RR'),'100000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('11','SEGUNDO INCLUIDO POR USER_APP VIA PACKAGE','24/890','2',to_date('18/04/18','DD/MM/RR'),'100000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('12','CLIENTE COM 5 PARAMETROS POR USER_APP VIA PACKAGE','24/890','2',to_date('18/04/18','DD/MM/RR'),'100000','MEDIO GRANDE');
Insert into USER_DEV.CLIENTE (ID,RAZAO_SOCIAL,CNPJ,SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA) values ('13','CLIENTE COM 3 PARAMETROS POR USER_APP VIA PACKAGE','14/890',null,to_date('18/04/18','DD/MM/RR'),null,null);
--------------------------------------------------------
--  DDL for Index CLIENTE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_DEV"."CLIENTE_ID_PK" ON "USER_DEV"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "USER_DEV"."CLIENTE" ADD CONSTRAINT "CLIENTE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "USER_DEV"."CLIENTE" ADD CONSTRAINT "CLIENTE_SEGMERCADO_FK" FOREIGN KEY ("SEGMERCADO_ID")
	  REFERENCES "USER_DEV"."SEGMERCADO" ("ID") ENABLE;
